[tool.poetry]
name = "mudev-backend"
version = "0.0.1"
description = ""
authors = ["MU-Software <musoftware@mudev.cc>"]
homepage = "https://mudev.cc"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.103.1"
pydantic = "^2.3.0"
redis = {version = "<5.0.0", extras = ["hiredis"]}  # celery 5.3.4 does not support ^5.0.0 yet
SQLAlchemy = "^2.0.21"
uvicorn = "^0.23.2"
gunicorn = "^21.2.0"
alembic = {extras = ["tz"], version = "^1.12.0"}
python-dotenv = "^1.0.0"
eventlet = "^0.33.3"
celery = {extras = ["redis", "sqlalchemy", "tblib"], version = "^5.3.4"}
gitpython = "^3.1.37"
aiohttp = "^3.9.0"
yt-dlp = "^2023.9.24"
pillow = "^10.0.1"
mutagen = "^1.47.0"
google-api-python-client = "^2.100.0"
ffmpeg-python = "^0.2.0"
pydantic-settings = "^2.0.3"
passlib = "^1.7.4"
argon2-cffi = "^23.1.0"
psycopg = {extras = ["binary"], version = "^3.1.12"}
typer = "^0.9.0"
python-dateutil = "^2.8.2"
flower = "^2.0.1"
ipython = "^8.18.1"
fabric = "^3.2.2"
toml = "^0.10.2"
email-validator = "^2.1.0.post1"
pyjwt = "^2.8.0"
user-agents = "^2.2.0"
typing-extensions = "^4.8.0"
python-multipart = "^0.0.6"
aiofiles = "^23.2.1"

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.4.0"
pylint = "^2.17.5"
flake8 = "^6.1.0"
mypy = "^1.5.1"
black = "^23.9.1"
bandit = "^1.7.5"
isort = "^5.12.0"
refurb = "^1.21.0"
flake8-noqa = "^1.3.2"
flake8-bugbear = "^23.9.16"
types-redis = "^4.6.0.7"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
