version: '3.9'

services:
  mudev-postgres:
    image: postgres:15.4
    platform: linux/arm64
    restart: unless-stopped
    environment:
      TZ: Asia/Seoul
      POSTGRES_USER: musoftware
      POSTGRES_PASSWORD: unknown_password
      POSTGRES_DB: mudev-db
    ports:
    - 25432:5432

  mudev-redis:
    image: redis:latest
    platform: linux/arm64
    restart: unless-stopped
    environment:
      TZ: Asia/Seoul
    ports:
    - 26379:6379
