#!/bin/sh
set -eux

docker build \
	-t $IMAGE_NAME \
	-f Dockerfile \
	--target runtime \
	--build-arg GIT_HASH="$(git rev-parse HEAD)" \
	--build-arg IMAGE_BUILD_DATETIME="$(date +%Y-%m-%d_%H:%M:%S)" \
	../
